Level.create( description: 'other' )
Level.create( description: 'certificate or diploma of less than one academic year' )
Level.create( description: 'certificate or diploma of at least one but fewer than two academic years' )
Level.create( description: "Associate's degree" )
Level.create( description: "certificate or diploma of at least two but less than four academic years" )
Level.create( description: "Bachelor's degree" )
Level.create( description: "Postbaccalaureate certificate" )
Level.create( description: "Master's degree" )
Level.create( description: "Post-master's certificate" )
Level.create( description: "Doctor's degree" )
Level.create( description: "None of the above or no answer" )
Level.create( description: "Not applicable" )
Level.create( description: "Information Not Available" )