Exercise.create( question: "Let's write a simple query.  Find all the available information about all the institutions.", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/2\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/1\">try again</a>?", answer: "* from institutions select ")

Exercise.create( question: "Find all available information about institutions where the city is <em>Athens</em>.", answer: "* = athens city from institutions select where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/3\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/2\">try again</a>?")

Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>stan</em>.", answer: "%stan% * chief from institutions like select where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/4\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/3\">try again</a>?")

Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>laura</em> or the chief's name contains the text <em>carroll</em>.", answer: "%carroll% %laura% * chief chief from institutions like like or select where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/5\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/4\">try again</a>?")

Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>laura</em> and the chief's name <strong>also</strong> contains the text <em>carroll</em>.", answer: "%carroll% %laura% * and chief chief from institutions like like select where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/6\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/5\">try again</a>?")
 
 
Exercise.create( question: "Find all available information about institutions from the city of <em>Houston</em> that are not in the state <em>TX</em>.", answer: "!= * = and city from houston institutions select state tx where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/7\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/6\">try again</a>?")

Exercise.create( question: "Find the name, city, and state of the institutions in which the chief's name contains the text <em>victor</em>.", answer: "%victor% chief city, from institutions like name, select state where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/8\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/7\">try again</a>?")

Exercise.create( question: "Find the name, city, and state of institutions from the state of <em>NY</em> in which the name of the institution contains the text <em>medical</em>.", answer: "%medical% = and city, from institutions like name name, ny select state state where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/9\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/8\">try again</a>?")

Exercise.create( question: "Find the institution name and the name of its locale institutions whose name contains the text <em>Penn State</em>.", answer: "%penn = and from institutions, institutions.locale_id institutions.name institutions.name, institutions.state, like locales locales.id locales.name select state% where ", response_correct: "Purrrrfect!  You're getting the hang of it now.  Try the <a href=\"exercises/10\">next exercise</a>!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/9\">try again</a>?")

Exercise.create( question: "Find the institution name and state and the name of its control for institutions whose city is <em>Sterling</em>.", answer: "= = and controls controls.id controls.name from institutions, institutions.city institutions.control_id institutions.name, institutions.state, select sterling where ", response_correct: "Purrrrfect!  You're all done!", response_incorrect: "Hmm.  The query you wrote ran successfully, but it didn't find the information I was looking for.  Would you like to <a href=\"exercises/10\">try again</a>?")
