Exercise.create( question: "Let's write a simple query.  Find all the available information about all the institutions.")
Exercise.create( question: "Find all available information about institutions where the city is <em>Athens</em>.")
Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>stan</em>.")
Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>laura</em> or the chief's name contains the text <em>carroll</em>.")
Exercise.create( question: "Find all available information about institutions where the chief's name contains the text <em>laura</em> and the chief's name <strong>also</strong> contains the text <em>carroll</em>.")
Exercise.create( question: "Find all available information about institutions from the city of <em>Houston</em> that are not in the state <em>TX</em>.")
Exercise.create( question: "Find the name, city, and state of the institutions in which the chief's name contains the text <em>victor</em>.")
Exercise.create( question: "Find the name, city, and state of institutions from the state of <em>NY</em> in which the name of the institution contains the text <em>medical</em>.")
Exercise.create( question: "Find the institution name and the name of its locale institutions whose name contains the text <em>Penn State</em>.")
Exercise.create( question: "Find the institution name and state and the name of its control for institutions whose city is <em>Sterling</em>.")